logging:
  config: classpath:logback.xml
  level:
    org.springframework.web: DEBUG


server:
  port: 8300

eureka:
  instance: 
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://yjh:yjh@192.168.16.54:8761/eureka/
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: sample-eureka-consumer